### PR TITLE
[AshleyClock/index.html] null initialization

### PR DESCRIPTION
**Pull request by 0xJoeMama**
You didn't have to use null here.

### CODE REVIEW

**Comment by BrianComics** [comment]
Oh, you're right! I didn't really think much about optimization or readability when writing the code since it was just a thirty minute project I threw together and hosted. When writing that, I needed a temporary variable that would immediately get overridden so I just used `null`. I also did a similar thing with the output element by making it display "Test Text" that is immediately overriden.

**Comment by 0xJoeMama** [comment]
Also, dqf is ashley?

**Comment by BrianComics** [comment]
Oh, Ashley is a friend that blocked on as a joke. She unblocked me a few months ago, but I just never took down the website. I acquired the Unix millisecond timestamp ( `1639703564426` -> Friday, December 17, 2021, 01:12:44 UTC ) that I was blocked using Discord snowflakes and threw together this website for fun.

**Comment by 0xJoeMama** [comment]
Oke, I thought you got turned down when asking a girl out lol. I was just worried about your mental state, considering that getting to the point where you make a fucking website to keep track of your sadness, is actually really concerning :concern:.

**Pull request merged**
